#!/usr/bin/php
<?php
declare(strict_types=1);

require_once __DIR__.'/vendor/autoload.php';

use Command\VkGetAuthUrl;
use Command\VkWallClear;
use Symfony\Component\Console\Application;
use Symfony\Component\Yaml\Yaml;

$config = Yaml::parseFile(__DIR__.'/config.yaml');
$application = new Application('Console apps', '1.0');

$application->add(new VkWallClear(null, $config));
$application->add(new VkGetAuthUrl(null, $config));

$application->run();
